module.exports = [
    {
        name: 'TOO EASY LOL',
        hash: 'NEEV6DHM',
        rows: 3,
        cols: 3,
    },
    {
        name: 'Squares',
        hash: 'H6ZYZX98',
        rows: 4,
        cols: 4,
    },
    {
        name: 'Broken Square',
        hash: 'JZNHPD67',
        rows: 4,
        cols: 4,
    },
    {
        name: 'Erased Snake',
        hash: 'JVCPD8A4',
        rows: 2,
        cols: 6,
    },
    {
        name: 'Arbitrary',
        hash: '2ZUGJBVD',
        rows: 3,
        cols: 3,
    },
    {
        name: 'One Solution',
        hash: '22YTTKSL',
        rows: 3,
        cols: 6,
    },
    {
        name: 'Overlap',
        hash: 'LY9L9CWE',
        rows: 2,
        cols: 4,
    },
    {
        name: 'Duplo Bricks',
        hash: 'TZYQ6SCT',
        rows: 4,
        cols: 4,
    },
    {
        name: "Let's Spin",
        hash: 'ED65C9C4',
        rows: 4,
        cols: 4,
    },
    {
        name: 'Totally Blocked',
        hash: 'NCYHGCZY',
        rows: 4,
        cols: 4,
    },
    {
        name: 'Hidden Path',
        hash: 'XLUMVWBS',
        rows: 4,
        cols: 4,
    },
    {
        name: 'Stepping Stool',
        hash: 'USC5X3XP',
        rows: 4,
        cols: 5,
    },
    {
        name: 'Black Hole Sun',
        hash: '2XKD2KA9',
        rows: 5,
        cols: 5,
    },
    {
        name: 'Tine',
        hash: 'HX6A62ZT',
        rows: 4,
        cols: 5,
    },
    {
        name: 'Oh No...',
        hash: '3A7AF59C',
        rows: 6,
        cols: 6,
    },
    {
        name: 'One Last Puzzle',
        hash: '6PB8LF8D',
        rows: 5,
        cols: 5,
    },
    {
        name: 'A Real Puzzle',
        hash: 'RD4YFLHR',
        rows: 9,
        cols: 9,
    },
    {
        name: 'Tetris Star',
        hash: 'BX7W2VV3',
        rows: 5,
        cols: 5,
    },
    {
        name: 'Anthropomorphism',
        hash: 'A9A4743D',
        rows: 5,
        cols: 5,
    },
    {
        name: 'Evil Stone Star Pillar',
        hash: 'A4AGFX5Y',
        rows: 4,
        cols: 6,
    },
    {
        name: 'Virtual Pillar',
        hash: 'E39A34DC',
        rows: 5,
        cols: 6,
    },
    {
        name: 'Pillar Expert',
        hash: 'FD7DCFCF',
        rows: 5,
        cols: 6,
    },
    {
        name: 'Got it all?',
        hash: 'T6NB5ZNN',
        rows: 7,
        cols: 7,
    },
    {
        name: 'Divided in Two',
        hash: 'E9FF73C5',
        rows: 4,
        cols: 9,
    },
    {
        name: 'Not Difficult',
        hash: '4CBAE969',
        rows: 5,
        cols: 5,
    },
    {
        name: 'Hell',
        hash: 'F6QDZM2N',
        rows: 5,
        cols: 10,
    },
    {
        name: 'Broken Copy',
        hash: '655BE3D3',
        rows: 6,
        cols: 9,
    },
];
