const { UP, DOWN, LEFT, RIGHT } = require('./arrowKeys');
const { puzzleEnum } = require('../simple_puzzles/puzzleEnum');

module.exports = [
    {
        id: '3adb72f3dda22a186d72700e190b228e1880a606',
        path: [UP, UP, UP, DOWN],
        action: (gpm) => {
            gpm.witnessManager.initiatePuzzles();
        },
    },
    {
        id: '????',
        path: [DOWN, DOWN],
        action: (gpm) => {
            gpm.simplePuzzleManager.initiatePuzzle(puzzleEnum.COMBO_LOCK);
        },
    },
    {
        id: '????',
        path: [LEFT, LEFT],
        action: (gpm) => {
            gpm.simplePuzzleManager.initiatePuzzle(puzzleEnum.CATSTERMIND);
        },
    },
    {
        id: 'ef361c8dc6409be689ea3bd26d6943152f615823',
        path: [
            UP,
            LEFT,
            DOWN,
            LEFT,
            UP,
            LEFT,
            DOWN,
            LEFT,
            UP,
            RIGHT,
            UP,
            RIGHT,
            UP,
            LEFT,
            UP,
            RIGHT,
            DOWN,
            RIGHT,
            UP,
            LEFT,
            UP,
            LEFT,
            UP,
            RIGHT,
            UP,
            LEFT,
            DOWN,
            LEFT,
            UP,
            RIGHT,
            UP,
            UP,
            LEFT,
            UP,
            RIGHT,
            DOWN,
            RIGHT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            DOWN,
            LEFT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            RIGHT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            RIGHT,
            DOWN,
            LEFT,
            DOWN,
            LEFT,
            DOWN,
            RIGHT,
            DOWN,
            RIGHT,
            DOWN,
            LEFT,
            LEFT,
            DOWN,
            RIGHT,
            DOWN,
            LEFT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            DOWN,
            RIGHT,
            UP,
            RIGHT,
            RIGHT,
            DOWN,
            DOWN,
            LEFT,
            UP,
            RIGHT,
            UP,
            LEFT,
            DOWN,
            LEFT,
            UP,
            LEFT,
            UP,
            LEFT,
            UP,
            RIGHT,
            RIGHT,
            UP,
            LEFT,
            UP,
        ],
        action: (gpm) => {
            console.log('original golden path');
        },
    },
    {
        id: '096f2da0ac6ecb18e501656de9e9a7cfa816b192',
        path: [DOWN, RIGHT, UP, LEFT, UP, RIGHT],
        action: (gpm) => {
            console.log('learning golden path');
        },
    },
    {
        id: '096f2da0ac6ecb18e501656de9e9a7cfa816b192',
        path: [DOWN, LEFT, UP, RIGHT, UP, LEFT],
        action: (gpm) => {
            console.log('learning golden path (alt)');
        },
    },
];
